apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lighttpd
  namespace: streaming
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
#    cert-manager.io/cluster-issuer: ${SECRET_NAME}
spec:
  ingressClassName: nginx
  tls:
    - secretName: ${SECRET_NAME}
      hosts:
        - paymetv.co.uk
  rules:
    - host: paymetv.co.uk
      http:
        paths:
          - path: /streaming(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: lighttpd
                port:
                  number: 80