apiVersion: v1
kind: Service
metadata:
  name: lighttpd
  namespace: streaming
  labels:
    app: lighttpd
spec:
  type: LoadBalancer
  loadBalancerIP: "paymetv.co.uk"  # Add your desired static IP here
  selector:
    app: lighttpd
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80