apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --namespace kafka -f docker-compose.yml
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
          image: wurstmeister/zookeeper:latest
          name: zookeeper
          ports:
            - containerPort: 2181
              protocol: TCP
      hostname: zookeeper
      restartPolicy: Always
